language: java
  
jobs:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.3

cache:
  directories:
  - $TRAVIS_BUILD_DIR/build/native/x86_64-unknown-linux-gnu
  - $TRAVIS_BUILD_DIR/build/native/x86_64-apple-darwin17.4.0
  
addons:
  homebrew:
    update: true
    packages:
      - ant@1.9
      - yasm
      - nasm
  apt:
    update: true
    packages:
      - yasm
      - nasm
      - automake1.11

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd $TRAVIS_BUILD_DIR/build/native/x86_64-unknown-linux-gnu; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cd $TRAVIS_BUILD_DIR/build/native/x86_64-apple-darwin17.4.0; fi
  - ls -lh
  - find . -name Makefile -exec touch {} \;
  - find . -name *.o -exec touch {} \;
  - find . -name *.a -exec touch {} \;
  - find . -name *.lo -exec touch {} \;
  - cd -

install: ant clean stage 

script: ant run-tests-native
