cache:
  directories:
  - $TRAVIS_BUILD_DIR/build/native/x86_64-unknown-linux-gnu
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y yasm
  - cd $TRAVIS_BUILD_DIR/build/native/x86_64-unknown-linux-gnu
  - ls -lh
  - find . -name Makefile -exec touch {} \;
  - find . -name *.o -exec touch {} \;
  - find . -name *.a -exec touch {} \;
  - find . -name *.lo -exec touch {} \;
  - cd -
language: java
install: ant clean stage 
script: ant run-tests-native
