# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: CI for MacOS

on:
  push:
    branches: [ CI-mutliplatform ]
  pull_request:
    branches: [ CI-mutliplatform ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install build deps
      run: brew install yasm; brew install nasm; brew install swig  
    - name: Build with Ant
      run: ant -Dbuild.configure.maintainer=true clean stage
